import { PartsData } from '../../../interfaces/partsdata';

export const PARTSDATA: PartsData[] = [
  {
    id: 1,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 2,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 3,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 4,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 5,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 6,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 7,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 8,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 9,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 10,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 11,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 12,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
  {
    id: 13,
    part_number: '123',
    description_en: 'English Part Number',
    description_es: 'Espanol Part Number',
    description_fr: 'French Part Number',
  },
];
